[Directories]
target_dir = C:\Shinseikai\BarcodePDF\preprocessing
processing_dir = C:\Shinseikai\BarcodePDF\processing
error_dir = C:\Shinseikai\BarcodePDF\error
done_dir = C:\pdfkarte\TmpPdf

[UI]
width = 600
height = 500

[Barcode]
contrast_factor = 2.0
render_zoom = 2.5
top_band_ratio = 0.15
min_barcode_width_ratio = 0.20

[Options]
auto_open_error_folder = True
start_minimized = False

[LOGGING]
log_retention_days = 14
log_directory = C:\Shinseikai\BarcodePDF\log
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = BarcodePDF